### ISSUE TITLE
I'm unable to decompile all the scripts using your decompiler

### ISSUE THREAD

**Issue by epsilon-0** [ColonolNutty/Sims4CommunityLibrary#1]
Can you maybe provide a bit more detailed example to the decompiler?

**Comment by ColonolNutty** [comment]
Some files only decompile with `unpyc3` and some only decompile using `py37dec`. I actually figured out a way to get it to switch between them if one or the other doesn't quite work. However, I haven't gotten around to including it within S4CL just yet.

Right now you would need to go into settings.py and change `py37dec` into `unpyc3` for the files that `py37dec` doesn't decompile properly.

**Comment by epsilon-0** [comment]
Ah, that makes a lot more sense :)
Thanks a lot.

Is there anyway to check which files are not decompiled correctly?

**Comment by epsilon-0** [comment]
I currently modified your autodecompile script as I am not using windows to play and code (so I don't use pycharm), and it seems like everything has decompiled (at least the simulation scripts, which are the only ones of interest).

**Comment by ColonolNutty** [comment]
At the end of a `py37dec` run, it'll give you a count of all the ones that failed to decompile, you'd have to manually go through the results to tell which ones failed. It's kind of counter intuitive the way I have it setup right now though. Perhaps tomorrow I can update them to use the scripts I have now.

**Comment by epsilon-0** [comment]
No worries, thanks a lot for this!

**Comment by ColonolNutty** [comment]
@epsilon-0 Try out the new decompiler and see if it works as you expect it to.

**Comment by epsilon-0** [comment]
Hmmm, it doesn't seem to be working.

Some debugging tells me that the py37dec.exe is the one causing the problems. Seems like it is unable to find the python executable if it is not the default python installation. I am using anaconda to manage the environments so seems like py37dec.exe fails.

**Comment by ColonolNutty** [comment]
I haven't changed that file. Was it saying that before?

**Comment by epsilon-0** [comment]
Ah, it was still failing before, so I had modified the decompiler.py to use only the unpyc3, which seemed to work nicely.

Is py37dec much better than unpyc3?

**Comment by ColonolNutty** [comment]
Most files I try to decompile don't work with unpyc3. That is why I default to py37dec.

**Comment by epsilon-0** [comment]
That's really interesting!
From my experience, it seemed like everything had decompiled correctly, maybe i missed something?

Give me some time, I'll check and report back.

But in any case doesn't seem like py37dec is going to be working for anyone who doesn't have a default windows python installation, which is a bummer, cuz my comp is linux. I'm seeing that this is very similar to scumbo's decompiler script, they might have given the py37dec source. Will check that as well.

**Comment by epsilon-0** [comment]
this is the py37dec source code: https://gitlab.com/fogity/python37-decompiler/tree/master

**Comment by ColonolNutty** [comment]
I actually didn't write the decompilers only modified them. I found them in various places.
