### ISSUE TITLE
Error Exception, can you help?

### ISSUE THREAD

**Issue by MiraMora** [ColonolNutty/Sims4CommunityLibrary#10]
[Sims4CommunityLib_Exceptions.txt](https://github.com/ColonolNutty/Sims4CommunityLibrary/files/5178439/Sims4CommunityLib_Exceptions.txt)

**Comment by ColonolNutty** [comment]
Looks like an error that occurred when a Sim was trying to route somewhere, but I'm not entirely sure what interaction they were performing when the error happened.

**Comment by MiraMora** [comment]
Yeah, I have the SOL mod and was trying to send my sim to the hospital but the error came up. It does that to almost everything I try to do :/

**Comment by ColonolNutty** [comment]
I'm going to figure out a way to log what interaction is actually causing the issue, so it can be debugged better in the future.

**Comment by MiraMora** [comment]
Thanks, take your time <3

**Comment by ColonolNutty** [comment]
See if you can reproduce the same issue with version 1.31 of S4CL. Then upload your log here. It may give us additional insight into which interaction is actually causing the error.

**Comment by MiraMora** [comment]
okay ill try that

**Comment by MiraMora** [comment]
its still the same with a few reactions but I could now do certain stuff without the error 
![2020-09-05 (1)](https://user-images.githubusercontent.com/70816606/92313200-9dcbe000-ef8e-11ea-8614-d48bb9bfa574.png)

**Comment by ColonolNutty** [comment]
Of course it's the same! Give me your log file!!!!

**Comment by MiraMora** [comment]
[Sims4CommunityLib_Exceptions.txt](https://github.com/ColonolNutty/Sims4CommunityLibrary/files/5178596/Sims4CommunityLib_Exceptions.txt)

**Comment by ColonolNutty** [comment]
Aha, the interaction name! Perfect: 
Error occurred while running _on_interaction_queued for interaction <SI KawaiiStacie: Visit_Hospital_Now id:122 sim:> with short name KawaiiStacie: Visit_Hospital_Now and display name hash: 11366770

**Comment by MiraMora** [comment]
Oh, thanks. Sorry I couldnt understand I didnt read that well lol

**Comment by MiraMora** [comment]
So it would be best if I just deleted it?

**Comment by ColonolNutty** [comment]
If you know of a way to contact the author of that mod, that would help them solve it, otherwise yeah, I'd just delete it or not even use the interaction.

**Comment by MiraMora** [comment]
OK, thanks again
