### ISSUE TITLE
unpyc3.py - Unresolved references

### ISSUE THREAD

**Issue by waaynee** [ColonolNutty/Sims4CommunityLibrary#11]
Hey,
I loaded the template project into PyCharm and followed the steps from the wiki. When I try to run compile_scripts.py there are unresolved references found in unpyc3.py.

`stmt_opcodes = {
    SETUP_LOOP, BREAK_LOOP, CONTINUE_LOOP,
    SETUP_FINALLY, END_FINALLY,
    SETUP_EXCEPT, POP_EXCEPT,
    SETUP_WITH,
    POP_BLOCK,
    STORE_FAST, DELETE_FAST,
    STORE_DEREF, DELETE_DEREF,
    STORE_GLOBAL, DELETE_GLOBAL,
    STORE_NAME, DELETE_NAME,
    STORE_ATTR, DELETE_ATTR,
    IMPORT_NAME, IMPORT_FROM,
    RETURN_VALUE, YIELD_VALUE,
    RAISE_VARARGS,
    POP_TOP,
}`

Would appreciate your help. Thanks in advance!

Edit: Installed Python 3.7.0

**Comment by ColonolNutty** [comment]
I'm guessing by the fact you closed this that you figured out the issue. :)

**Comment by waaynee** [comment]
Yes, the unresolved references are no problem. The script still works 👍🏻
