### ISSUE TITLE
Devious Devices/Discord

### ISSUE THREAD

**Issue by BlackSuperman10296** [ColonolNutty/Sims4CommunityLibrary#16]
...

**Comment by ksmercedes** [comment]
Hey, I am also very sad about it. I sign up here only to come in contact with you. I love your mods sooo much. I would so happy to get the discord link, too. Because I don't want to play with out them.

**Comment by ayamane200** [comment]
Hey dud, sorry for you, I loved your content... Do upload your mods here ? If no, then can you give me the link to your discord too please, I would gladly continue playing with your creation

**Comment by lunaterasu** [comment]
discord pls

**Comment by nawalony2** [comment]
Without your mod is not the same, discord link plz :(

**Comment by ColonolNutty** [comment]
This is absolutely without a doubt the **worst** repository you could have ever asked for Not Safe For Work content on.
