### ISSUE TITLE
Missing  stereo speaker icon on the phone's option

### ISSUE THREAD

**Issue by Ellanor** [ColonolNutty/Sims4CommunityLibrary#17]
Hi, (I apologize in advance in case I was posting in the wrong place), I noticed that using the S4CL from version 1.66 the stereo speaker icon on the phone's option is missing and the problem was not solved by updating to the latest version.
I tried to start the game without mod (everything ok) and then just inserting S4CL and in this case the issue came back. 
Here is an image that better explains the problem.

![](https://i.imgur.com/qjkToAo.png)
The Sims 4 version 1.75.125.1030
Platform: PC
Sims4CommunityLibrary v1.67

**Comment by ColonolNutty** [comment]
A better place to ask for support is in my discord: https://discord.gg/fdCgyXkDZb

**Comment by ColonolNutty** [comment]
Please see my reply to #19
