### ISSUE TITLE
can you help me with a Exception? 

### ISSUE THREAD

**Issue by lilyshura** [ColonolNutty/Sims4CommunityLibrary#18]
[Sims4CommunityLib_Exceptions.txt](https://github.com/ColonolNutty/Sims4CommunityLibrary/files/7151313/Sims4CommunityLib_Exceptions.txt)

**Comment by lilyshura** [comment]
the error comes when I send my sim to do my university homework

**Comment by ColonolNutty** [comment]
That error is too generic to determine the cause. A better place to ask for support is in my discord: https://discord.gg/fdCgyXkDZb
