### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by bloodconfetti** [ColonolNutty/Sims4CommunityLibrary#2]
Sorry. I feel like I'm just... the most stupid, but I cannot figure out what I'm doing.

The instructions given are as follows:

> Installation:

    Download the zip archive from the download link
    Unpack the archive using your favorite archiving tool.
    Drag the files/folders to your Mods directory.
    Keep in mind the ts4script file MUST be either top level (Directly in the Mods/ folder) or one folder deep (Mods/Blah/). Any deeper and it will not work.

I clicked on 'clone or download' and 'download zip' then extracted the file to my Documents folder, and then moved it to my Mods folder. But there's not a .ts4script that I can see anywhere... so it's definitely not within reach to be able to run, if it exists. And I continued to get the exception error...
[lastException.txt](https://github.com/ColonolNutty/Sims4CommunityLibrary/files/4110707/lastException.txt)
[Sims4CommunityLib_Messages.txt](https://github.com/ColonolNutty/Sims4CommunityLibrary/files/4110708/Sims4CommunityLib_Messages.txt)
But the Library itself says all tests were successful. So maybe this has nothing to do with your Library. I'm just unsure, sorry. I don't know how to read these things...

**Comment by ColonolNutty** [comment]
https://github.com/ColonolNutty/Sims4CommunityLibrary/releases/tag/v1.2.6

**Comment by ColonolNutty** [comment]
You have to get it from the Releases.

**Comment by bloodconfetti** [comment]
Oh thank you! Should the Master folder be removed from my Mods folder once I have the package and ts4script installed? Because I did download from your link (thank you so much!) and extracted them to the Mods folder, and still encountered this exception:
[lastException.txt](https://github.com/ColonolNutty/Sims4CommunityLibrary/files/4110735/lastException.txt)
Again, I very much apologize if I'm misunderstanding and this has nothing to actually do with the Library. And thank you for your time, and your mods!

**Comment by ColonolNutty** [comment]
Yeah, you shouldn't install the source code.

**Comment by ColonolNutty** [comment]
I updated the readme, hopefully it makes more sense now.

**Comment by bloodconfetti** [comment]
Thank you so so much for your help!
