### ISSUE TITLE
Add a game folder variable 

### ISSUE THREAD

**Issue by Kondratova** [ColonolNutty/Sims4CommunityLibrary#22]
If you have in settings.py exception like
`raise Exception('The Sims 4 game folder was not found! Please specify one manually in settings.py.') `

it would be logical to add a variable such as
`my_game_folder = ''`

and change the code as follows
```
        # Windows
        if my_game_folder:
            game_folder = os.path.join(my_game_folder)
        else:
            import winreg as winreg
            key = winreg.OpenKey(winreg.HKEY_LOCAL_MACHINE, 'SOFTWARE\\Maxis\\The Sims 4')
            (game_folder, _) = winreg.QueryValueEx(key, 'Install Dir')

        print(f'Game folder path: {game_folder}')
```
so that users don't change your code below the line if your code didn't find the path.

Sorry for my English, it's not my native language, I could be mistaken.
It's just a suggestion.

**Comment by ColonolNutty** [comment]
Is this a suggestion for the template project? Because I think you put the issue in the wrong project: https://github.com/ColonolNutty/s4cl-template-project

**Comment by Kondratova** [comment]
You're right,sorry, I opened the wrong tab
