### ISSUE TITLE
Player Sims can't Assault Each Other?

### ISSUE THREAD

**Issue by Malacosoma** [ColonolNutty/Sims4CommunityLibrary#3]
Hi! I'm trying to get one of my Sims to assault another one. The option to attempt the assault is there, but when I choose it the icon flashes for like a second before disappearing, and the two Sims just stand there chatting. These Sims are enemies. They hate each other, I have one toggled for allowing to assault and the other toggled to allow being assaulted, but it doesn't change anything.

**Comment by Malacosoma** [comment]
Now the option to assault isn't there, despite it still being enabled...

**Comment by ColonolNutty** [comment]
This is NOT the place to report issues with mods that utilize S4CL. If you have a problem associated with S4CL, this is where you report it. However, you need to bring your question to the mod you are having a problem with.
