### ISSUE TITLE
Creative Commons License Violation

### ISSUE THREAD

**Issue by charitycodes** [ColonolNutty/Sims4CommunityLibrary#5]
This statement in README.md is in violation of the chosen license:

"YOU DO NOT HAVE MY PERMISSION TO BUNDLE S4CL INTO YOUR OWN MOD. So don't do it. Redirect the users of your mod to the github repository or releases pages instead."

From https://creativecommons.org/licenses/by/4.0/

"Share — copy and redistribute the material in any medium or format
Adapt — remix, transform, and build upon the material
for any purpose, even commercially.
This license is acceptable for Free Cultural Works.
The licensor cannot revoke these freedoms as long as you follow the license terms.
Under the following terms:
Attribution — You must give appropriate credit, provide a link to the license, and indicate if changes were made. You may do so in any reasonable manner, but not in any way that suggests the licensor endorses you or your use."

As long as someone gives credit and provides a link, the library may be bundled, changed and included in a mod. Your license prevents you from revoking this privilege. I suggest you remove that line from README.md or change your license. I'm not trying to get around what you want, but it is frustrating to find a restriction at the bottom of the readme that you didn't expect to be there based on the license. I would have liked to use and contribute to this project. As it stands, I will have to pass.

**Comment by ColonolNutty** [comment]
I don't see why you would need to bundle S4CL in your mod.

**Comment by ColonolNutty** [comment]
Fixed. Check the readme once more.

**Comment by charitycodes** [comment]
That makes sense, thanks. And yes, the new README is consistent with the license. I didn't dig into the code yet, so I didn't know if there would be a reason to bundle it or not. Mostly, I was considering forks of the library that had been modified.
