### ISSUE TITLE
Error Upon Loading

### ISSUE THREAD

**Issue by M4NDYP4ND7** [ColonolNutty/Sims4CommunityLibrary#7]
I have had trouble the past few days since the WW update. Every time I load into my household, I am bombarded with errors about the WP mod. I have had to remove it and the animations completely in order to even play my game. I was hoping that your last update would fix this, but it is still not working as of today. I have been using mods for years. So, I know I am installing everything correctly. And I also am sure that there are not any other mods interfering since the message is clear that it is WP causing the problem. Please consider taking a look.
[Wicked_Pets_Exceptions.txt](https://github.com/ColonolNutty/Sims4CommunityLibrary/files/4939845/Wicked_Pets_Exceptions.txt)
[Kinky_Whims_Exceptions.txt](https://github.com/ColonolNutty/Sims4CommunityLibrary/files/4939846/Kinky_Whims_Exceptions.txt)
[Sims4CommunityLib_Exceptions.txt](https://github.com/ColonolNutty/Sims4CommunityLibrary/files/4939847/Sims4CommunityLib_Exceptions.txt)
[lastException_63730681274.txt](https://github.com/ColonolNutty/Sims4CommunityLibrary/files/4939848/lastException_63730681274.txt)

**Comment by ColonolNutty** [comment]
This is an extremely inappropriate place to report issues unrelated to S4CL. Please seek help in the appropriate support threads.
