### ISSUE TITLE
Error message in Sims4CommunityLib_Exceptions

### ISSUE THREAD

**Issue by Lhoavtee** [ColonolNutty/Sims4CommunityLibrary#8]
[Sims4CommunityLib_Exceptions.txt](https://github.com/ColonolNutty/Sims4CommunityLibrary/files/4944906/Sims4CommunityLib_Exceptions.txt)

**Comment by ColonolNutty** [comment]
Looks like an error related to a mod with this in the name? `maeemma_pregnant_xmlinjector`. It appears to have something to do with pregnancies. The name of the author may be `maeemma`

**Comment by Lhoavtee** [comment]
Thank you both for the assistance and for making many entertaining mods. It seems to be running smoothly now.
